# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'infracollab'
  dockerRegistryServiceConnection: 'InfraCollab Azure Container Registry'

stages:
- stage: Build
  displayName: Build Container Image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image to Azure Container Registry (ACR)
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Task1/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push an image to Azure Container Registry (ACR)
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)