# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: |
    '$(Build.BuildId)'
    '$(Build.BuildNumber)'
  imageRepository: 'infracollab'
  dockerRegistryServiceConnection: 'InfraCollab Azure Container Registry'

stages:
- stage: Build_and_Push_Container_Image
  displayName: Build and Push Container Image
  jobs:  
  - job: Build and Push
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Container Image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Task1/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push Container Image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)